"""
Phase 7 (cont'd) — SQLite persistence layer.

Stores every alert generated by the detection pipeline so the
/alerts and /statistics endpoints, and eventually the dashboard,
have real historical data to read from instead of only seeing
the result of the single most recent /analyze call.
"""

import sqlite3
import json
import os

DB_PATH = os.path.join(os.path.dirname(__file__), "alerts.db")


def get_connection():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def init_db():
    """
    Creates the alerts table if it doesn't already exist.
    Safe to call every time the app starts.
    """
    conn = get_connection()
    conn.execute("""
        CREATE TABLE IF NOT EXISTS alerts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT NOT NULL,
            flow_id TEXT NOT NULL,
            source_file TEXT,
            src_ip TEXT NOT NULL,
            src_port INTEGER,
            dst_ip TEXT NOT NULL,
            dst_port INTEGER,
            protocol TEXT,
            threat_class TEXT NOT NULL,
            confidence REAL NOT NULL,
            severity TEXT NOT NULL,
            risk_score INTEGER NOT NULL,
            evidence TEXT NOT NULL
        )
    """)
    conn.commit()
    conn.close()


def insert_alert(alert, source_file):
    """
    Persists a single alert dict (as produced by detector.detect(),
    enriched with flow_id/timestamp in main.py) into the database.
    """
    conn = get_connection()
    conn.execute("""
        INSERT INTO alerts (
            timestamp, flow_id, source_file, src_ip, src_port,
            dst_ip, dst_port, protocol, threat_class, confidence,
            severity, risk_score, evidence
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (
        alert["timestamp"],
        alert["flow_id"],
        source_file,
        alert["src_ip"],
        alert["src_port"],
        alert["dst_ip"],
        alert["dst_port"],
        alert["protocol"],
        alert["threat_class"],
        alert["confidence"],
        alert["severity"],
        alert["risk_score"],
        json.dumps(alert["evidence"]),
    ))
    conn.commit()
    conn.close()


def get_alerts(threat_class=None, severity=None, limit=100):
    """
    Returns stored alerts, newest first, with optional filters.
    """
    conn = get_connection()

    query = "SELECT * FROM alerts WHERE 1=1"
    params = []

    if threat_class:
        query += " AND threat_class = ?"
        params.append(threat_class)

    if severity:
        query += " AND severity = ?"
        params.append(severity)

    query += " ORDER BY id DESC LIMIT ?"
    params.append(limit)

    rows = conn.execute(query, params).fetchall()
    conn.close()

    alerts = []
    for row in rows:
        alert = dict(row)
        alert["evidence"] = json.loads(alert["evidence"])
        alerts.append(alert)

    return alerts


def get_statistics():
    """
    Computes aggregate counts directly from stored alerts.
    All numbers are derived from real data - nothing fabricated.
    """
    conn = get_connection()

    total_alerts = conn.execute(
        "SELECT COUNT(*) FROM alerts"
    ).fetchone()[0]

    critical_alerts = conn.execute(
        "SELECT COUNT(*) FROM alerts WHERE severity = 'CRITICAL'"
    ).fetchone()[0]

    by_threat_class = conn.execute("""
        SELECT threat_class, COUNT(*) as count
        FROM alerts
        GROUP BY threat_class
    """).fetchall()

    by_severity = conn.execute("""
        SELECT severity, COUNT(*) as count
        FROM alerts
        GROUP BY severity
    """).fetchall()

    conn.close()

    return {
        "total_alerts": total_alerts,
        "critical_alerts": critical_alerts,
        "by_threat_class": {row["threat_class"]: row["count"] for row in by_threat_class},
        "by_severity": {row["severity"]: row["count"] for row in by_severity},
    }